TD22057/insteon-mqtt

HISTORY.md, insteon_mqtt/mqtt/KeypadLinc.py
Fixes #34.  There are other issues remaining with scenes.  This is a very targeted update that does not address all of them.  One item to check:  I don't understand the extraction of `group` from `data` that some devices are doing.  I templated these changes from the working `handle_set()` method.  I noticed that Switch and Dimmer also attempt to get `group` from `data` in their `handle_scene()` methods.  Is this really correct?  Should KeypadLinc also do this?  ...only if the `group` argument to the method is `None`?
=> KeypadLinc uses correct handler for scene commands

config.yaml
The leak topic example for Home Assistant does not work as it seems /leak is not valid. I got it to work by using /wet instead.
Sorry for the previous PR, I selected the wrong branch.
=> Fix topic example for leak sensor and Home-Assistant

insteon_mqtt/cmd_line/device.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/db/Device.py, insteon_mqtt/device/Base.py, tests/db/test_Device.py, tests/handler/test_StandardCmd.py
Adds a get_engine command that can be used to get the engine
version which is saved in the device.db.
~~When refresh is called, if the engine version is not known,
it will be requested.~~
One step in process to fix https://github.com/TD22057/insteon-mqtt/issues/17
=> Add Support for Engine Version

insteon_mqtt/db/Device.py
Chalk this up to Pytest catching an error that might have slipped
through for a while.
I don't see any reason why a db couldn't have two entries for the
same thing, one in use and one not.  I think the Pytest was right
here.
=> Only Remove DeviceEntry from Group if Matches Memory Location

insteon_mqtt/Protocol.py, insteon_mqtt/message/InpStandard.py, tests/message/test_InpExtended.py, tests/message/test_InpStandard.py, tests/test_Protocol.py
Keeps a list of messages that have not expired.  A non-expired message is one in which the time for the remaining hops to occur has not yet passed.
If a subsequent incoming message matches one of these, it is ignored with an info message to the log.
Fixes #42
=> Catch and Ignore Duplicate Incoming Messages

insteon_mqtt/message/OutStandard.py, tests/message/test_OutExtended.py
The selection of CRC_Type was buried in to_bytes() which is only called at the protocol level when sending a message.  Making it unhelpful.
I moved the CRC_Type to the constructors so that it can be designated at the time the message is created.  This is necessary for adding thermostat functionality.
=> Move Extended Message CRC_Type to Constructor

insteon_mqtt/handler/ExtendedCmdResponse.py, insteon_mqtt/handler/__init__.py, tests/handler/test_ExtendedCmdResponse.py
These responses have a standard length ACK followed by an extended
lendth direct message with the requested payload.
These are used by the thermostat and likely by other devices as
well.
=> Add Handler for Extended Length Responses

config.yaml, insteon_mqtt/config.py, insteon_mqtt/device/Thermostat.py, insteon_mqtt/device/__init__.py, insteon_mqtt/handler/ThermostatCmd.py, insteon_mqtt/handler/__init__.py, insteon_mqtt/mqtt/Thermostat.py, insteon_mqtt/mqtt/__init__.py, insteon_mqtt/mqtt/config.py, tests/device/test_Thermostat.py, tests/mqtt/test_ThermostatMqtt.py
This adds a good level of support for the Insteon Thermostat.  It works reasonably well with the MQTT Climate component in Home Assistant, however the MQTT Climate doesn't distinguish between heat and cool setpoints.  These are really necessary to make auto and program work correctly.  Hopefully in the next day or so I will be able to submit a PR to Home Assistant to make those changes to MQTT Climate.
This should be merged after Meta_Storage #92 as this includes that PR.
=> Add Support for Insteon Thermostat

insteon_mqtt/db/Device.py, insteon_mqtt/db/DeviceModifyManagerI1.py
Fixes a subtle bug.  In some instances the start_modify function
needs to be called by a command sequence.  In those cases, it
needs to accept an on_done argument and needs to call that
on_done function (the command sequence callback) when complete.
=> Add on_done Callback to allow for calling by a Sequence

insteon_mqtt/cmd_line/device.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/device/Base.py
Mostly a command sequence.  Checks to see what the engine version
is, since linking will not work on i1 devices and is not required
for i2 devices.
If the device is i2cs, creates the modem->device link which is
the only one required for the modem to talk to the device.
Join is an idempotent (what a word!) function.  It will not
alter the state of the device more than necessary if run
multiple times.
I chose the word JOIN as I think it gives the right connotation
to the user even though it isn't an insteon term.  But this way
it won't be confused with a link or pair operation.  So new users
can quickly be instructed to join without leading to confusion.
Closes #97
=> Add Join Command a Batch Linking Command

docs/hassio_quick_start.md, docs/mqtt.md, docs/quick_start.md
This adds documentation for the new Join command.  It strongly pushes users into using it and suggests a workflow of Join, Pair, Sync for new devices.  I revised the 'linking' command to be noted as slightly more advanced option or one that can be used when other things are not working.
I also added thermostat notes mostly taken from the writing I put into the config file.
=> Add Documentation for Join Command and Thermostat

docs/mqtt.md, insteon_mqtt/cmd_line/device.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/db/Device.py, insteon_mqtt/device/Base.py, insteon_mqtt/handler/BroadcastCmdResponse.py, insteon_mqtt/handler/__init__.py, tests/db/test_Device.py, tests/handler/test_BroadcastCmdResponse.py
Get Model command will query the device for its device category, sub-category, and firmware version.
This information is usually sufficient to determine the device model and its full set of capabilities.
A Get Model command will run on refresh if:
1. The model number is not currently known; OR
2. Force on refresh is true
The Get Model command can also be run independently via mqtt or the command line.
Adds testing for the function and documentation as well.
Required a "Broadcast Command Handler" as the model information is returned in a broadcast packet (thanks smart labs).
Fixes #55
=> Add Get Model Command; Run on Refresh if not Known

insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/FanLinc.py, insteon_mqtt/device/IOLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Switch.py, insteon_mqtt/device/Thermostat.py, insteon_mqtt/handler/DeviceDbGet.py, insteon_mqtt/handler/DeviceDbModify.py, insteon_mqtt/handler/ExtendedCmdResponse.py, insteon_mqtt/message/InpStandard.py, tests/message/test_InpStandard.py
Decode and report available error codes.  Should help users solve some issues.
I wish there was some central place to do this, but in order to get the proper messaging out to the user this has to be reported rather high up in the stack.
Closes #95
=> Parse and Report I2CS NAK Error Codes

insteon_mqtt/Modem.py, insteon_mqtt/db/Device.py, insteon_mqtt/db/DeviceEntry.py, insteon_mqtt/device/Base.py
This only deals with the device level db, not the modem yet.
Handles three variations of config file defintions.
Adds the concept of data_1, data_2, and data_3 keys in a definition.
=> Parse Config Scenes into DB_Config

docs/mqtt.md
The `set_button_led` command uses `group`, not button.
> TypeError: set_button_led() got an unexpected keyword argument 'button'
=> Fix KeypadLinc command doc

insteon_mqtt/db/Device.py, insteon_mqtt/db/DeviceModifyManagerI1.py, tests/db/test_DeviceModifyManagerI1.py
Fixes a small bug where writes to an i1 database were not being
updated in the software database.  They were only being fixed
by a refresh.
This brings i1 inline with how i2 and above devices work.
=> Save Writes to i1 Device DB to Software Database

docs/mqtt.md, insteon_mqtt/device/Thermostat.py, insteon_mqtt/handler/ThermostatCmd.py
Fixes TD22057\#142
Ambient Temp push messages are in 2x format.
Add get_status to normal refresh commands.  Ensures that we have
the proper units (C or F) set.  Otherwise we may misinterpret
temp messages.
Add more documentation to try and make things easier to understand.
=> Fix Ambient Temp Calculation in Thermo; Add More Documentation

docs/mqtt.md, insteon_mqtt/catalog.py, insteon_mqtt/device/Motion.py
This enables the software control of flags on the motion sensor. This includes the on-only mode, the night only mode, the LED on and off, the light sensitivity, and the length of timeout.
There are some distinctions between the older 2842 models of motion sensor and the newer 2844 models of motion sensor. This attempts to accommodate both of them.
Updated documentation.
Closes #184
=> Enable Software Control of Motion Sensor Flags

docs/mqtt.md, insteon_mqtt/Modem.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/cmd_line/modem.py, insteon_mqtt/device/Base.py
Battery devices will be skipped by default unless the battery arg is true.
This is pretty helpful if you have a lot of devices on the initial setup on your network.
Similarly I added a get_engine_all function.  I still have ~20 i1 devices that can't be refreshed until the get_engine command is run.  Again, this is really only necessary for the initial setup, but it is very handy.  The need for this command should diminish as the i1 devices break or are replaced.
=> Option to Skip Battery Devices on Refresh;  Add Get_Engine_All Function

insteon_mqtt/Modem.py, insteon_mqtt/Protocol.py, insteon_mqtt/device/Base.py, insteon_mqtt/handler/ModemScene.py, insteon_mqtt/message/InpAllLinkFailure.py, insteon_mqtt/message/InpStandard.py, insteon_mqtt/message/OutStandard.py
Solves issues with:
1. Timeouts because of a lot of AllLink Cleanup messages coming in.
2. Better handle failed scene commands by changing the successful devices.
3. Properly warn users about failures with error messages.
Ironically, this includes fixing a bug that is caused by an error in the Insteon documentation.  The same bug I fixed almost exactly seven years ago in MisterHouse.  Seven years working on Insteon, ugh, I would never have expected that.
=> Handle Housekeeping Messages Sent to Modem During Scene Command

insteon_mqtt/Modem.py
Two errors.  One was a holdover from when I tried logging inside
command sequences.
The other is caused by the different arguments for add_on_device
between devices and the modem.
Fixes #192
Fixes #193
=> Fix Bad Coding in Modem Sync_Add and Sync

insteon_mqtt/device/Thermostat.py
Modem responder group is likely ignored, but standard practice
is to set this to 0x01.  This fixes that mistake.
May solve #154, may not
=> Modem Responder Group from Thermostat Should be 0x01

insteon_mqtt/network/Mqtt.py
The `id` key in the `mqtt` section of the configuration can be used to
supply a unique ID for each service instance.
When multiple insteon-mqtt services are connected to the same MQTT broker,
they could be configured to use separate topics, but not separate client IDs.
This resulted in the broker breaking the connections as the services connected
and reconnected.
=> Add configuration key for MQTT client ID

docs/scenes.md
the links were broken making github try to open docs/docs/mqtt.md Since file is in same directory dont need docs/
=> updated two mqtt command links

insteon_mqtt/network/Mqtt.py
The Paho-MQTT client may not invoke the 'on_disconnect'
callback when used with an external loop, so check for connection
loss during calls to loop_misc() and handle it appropriately.
Closes #222.
=> Detect disconnections during poll() calls

insteon_mqtt/handler/DeviceDbGet.py, insteon_mqtt/handler/DeviceDbModify.py, insteon_mqtt/handler/DeviceRefresh.py
This issue was discovered in part by #231 
For some reason we had 0 retries on DB_Modify, which was wrong.  This changes that to the default 3.
_-- Update see comment below, we can have retry of 3 for the initial get message --_
Also, it became clear why the DB_Get handler must have a retry of 0.  The handler only sends a single request and then waits for numerous extended messages from the device.  If the time between messages from the device exceeds the time_out, there is really nothing we can do.  There is no way to ask the device to resume from that point.  In fact, asking again while the device is still responding seems to just be ignored by the device.
So instead, this increases the time_out for this particular handler.  It should decrease some errors with little side effect.  If …
=> Don't Retry DB Get But Increase Timeout; Retry on DB Modify

HISTORY.md, insteon_mqtt/db/Device.py, insteon_mqtt/db/DeviceModifyManagerI1.py, insteon_mqtt/handler/DeviceDbModify.py
This should dramatically decrease the number of full refreshes of a device and should speed things up.
My recollection is that there may be a few other instances in which i1 devices increment this value.  But I think those are all related to peek/poke operations.  I don't think set_flags should cause this to change.
Closes #232
=> Increment Database Delta on Writing

config.yaml, insteon_mqtt/config.py, insteon_mqtt/device/EZIO4O.py, insteon_mqtt/device/__init__.py, insteon_mqtt/mqtt/EZIO4O.py, insteon_mqtt/mqtt/__init__.py, insteon_mqtt/mqtt/config.py, tests/mqtt/test_EZIO4O.py, tests/mqtt/test_config.py, tests/util/helpers/main.py
This add support for Smartenit EZIO4O 4 relay output module. This PR implements the usual state, set and scene MQTT features for the 4 outputs. Usage is similar to the KeypadLinc buttons.
Control of the device register flag is also implemented.
Scene support is done through modem scene (ALL-Link-Broadcast messages).
Like with KeypadLinc buttons, edit scenes.yaml to associate each EZIO4O output with a different modem group and other Insteon devices.
=> Add support for EZIO4O

HISTORY.md, insteon_mqtt/Modem.py, insteon_mqtt/db/Device.py, insteon_mqtt/db/DeviceEntry.py, insteon_mqtt/db/DeviceScanManagerI1.py, insteon_mqtt/db/Modem.py, insteon_mqtt/db/ModemEntry.py, insteon_mqtt/handler/DeviceDbGet.py, insteon_mqtt/handler/ModemDbGet.py, insteon_mqtt/handler/ModemLinkComplete.py, tests/db/test_Device.py, tests/db/test_DeviceEntry.py, tests/db/test_DeviceEntryI1.py, tests/db/test_DeviceModifyManagerI1.py, tests/db/test_DeviceScanManagerI1.py, tests/db/test_Modem.py, tests/db/test_ModemEntry.py, tests/handler/test_ModemDbGet.py, tests/test_Scenes.py
Straightforward, this now additionally prints the device name if the device exists when printing database entries.  This makes them much easier to read.
If the device cannot be found, just the address is printed.
I also cleaned up some formatting so database entries appear consistent for easier reading.
Closes #166
=> Print Device Names When Printing a Device's Database

HISTORY.md, insteon_mqtt/cmd_line/device.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/db/Device.py, insteon_mqtt/device/Remote.py
This requires merging #240 first.
This is a new feature which will check the battery level for 2342-xxx remotes at most once every 4 days.  The device is generally asleep, so the message is sent just after receiving a message from the device when it is awake.  This means you will not get battery warnings from devices that you do not use.
If the battery voltage is low, a message will be emitted to the Low_Battery topic.
Closes #49
=> Check the Remote Battery Periodically and Report to Low Battery Topic

docs/mqtt.md, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/util.py
This adds support for setting the ramp rate using the set_flags command. It supports a value between 0 and 31. I've tested locally on real hardware and setting the rate works without any issue. The changes I've made are basically a duplicate of the set_on_level method.
=> Support for the default ramp rate setting for Dimmer and KeypadLinc

insteon_mqtt/Scenes.py, insteon_mqtt/db/Device.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/FanLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Remote.py, tests/test_Scenes.py
This change fixes a handful of problems that I identified while attempting to use the scene import/sync capabilities of insteon_mqtt with my existing Insteon network that includes an Insteon Hub (2245-222) and that has several preexisting scenes, some of which involve the hub.
These are being submitted in a single pull request because some of the changes depend on changes made in earlier commits in the same chain.  Please let me know if you feel it is important to split these into multiple PRs.
@krkeegan I would very much appreciate your code review of these changes, since you wrote much of the content that is being changed here.
Each of the issues/fixes is summarized below.
**Issues fixed:**
**Issue 1:** Multiple dimmer scenes are being combined by compress_controllers() despite having …
=> Scene fixes

config.yaml
Home Assistant expects upper-case on/off payloads.  Also, update HA MQTT config examples for recent IOLinc changes.
Dog-food tested with these payload changes and HA MQTT config topic changes as part of testing done for #256.
=> IOLinc config.yaml fixes

HISTORY.md, insteon_mqtt/device/Base.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/FanLinc.py, insteon_mqtt/device/IOLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Outlet.py, insteon_mqtt/device/Switch.py, insteon_mqtt/device/Thermostat.py, insteon_mqtt/handler/BroadcastCmdResponse.py, insteon_mqtt/handler/DeviceDbGet.py, insteon_mqtt/handler/DeviceDbModify.py, insteon_mqtt/handler/DeviceRefresh.py, insteon_mqtt/handler/ExtendedCmdResponse.py, insteon_mqtt/handler/StandardCmd.py, insteon_mqtt/handler/StandardCmdNAK.py, insteon_mqtt/handler/__init__.py, insteon_mqtt/message/InpStandard.py, insteon_mqtt/mqtt/Leak.py, insteon_mqtt/mqtt/Remote.py, tests/device/test_IOLinc.py, tests/handler/test_BroadcastCmdResponse.py, tests/handler/test_DeviceDbGet.py, tests/handler/test_ExtendedCmdResponse.py, tests/mqtt/test_Remote.py
A NAK with the cmd2 value of `0xFC = Pre NAK in case database search takes too long ` see [Insteon Notes](http://cache.insteon.com/developer/i2CSdev-022012-en.pdf)
There is no other documentation of this, and @jonsmirl appears to be the first person to report this in #231.  Based on what I see, it seems that this NAK can show up whenever, even when not searching the DB.
It appears the proper way to handle this is just to reset the message timeout and do nothing else.
This solves many of the issues of #231
=> Properly Handle Pre-NAK Response

HISTORY.md, insteon_mqtt/db/Device.py, tests/db/test_Device.py
Fix the database object to reflect the possibility that the last entry may not be an unused entry.
If the last entry is used, when adding entries to new memory locations, add an additional blank unused entry so that the last entry is unused.
Not exactly what the original issue was opened about, but this was the result of the review.
Closes #250
=> Last Entry Can be Used

insteon_mqtt/handler/Broadcast.py, tests/handler/test_Broadcast.py
This fixes a problem that I noticed recently where when some broadcast messages aren't received by my PLM and the corresponding cleanup message is received, the cleanup message is being dropped by Insteon-MQTT.  Upon digging in to the code, I noticed that the Broadcast handler had been written to attempt to avoid double-handling broadcasts and their corresponding cleanup messages by dropping any cleanup messages that follow a broadcast from the same device.  In the case of my i2cs devices, this meant that even if a Success Report Broadcast message from a previous button press had been received, then a cleanup message for a subsequent button press would be treated as a duplicate of the Success Report Broadcast message.
To fix, I made the Broadcast handler's duplicate check also consider …
=> Don't treat different broadcast msgs from same device as duplicate

HISTORY.md, insteon_mqtt/Protocol.py
These are rare since we do a good job with our message timings but I think they are still happening for some people.  Right now when they happen they most likely get reported as lacking a 0x02 starting byte.
This adds a brief delay if one doesn't already exist and reports the info message to the log.
=> Parse, report and delay on receiving a PLM Busy Signal

HISTORY.md, config.yaml, tests/test_Integration.py
I don't have a lot of experience with pytest and mocking.  So this may be a little bit crude.
I managed to patch enough of the entire stack to enable testing of integration from pushing an mqtt message and testing the resulting message written by the modem.  Similarly the inverse is also possible you can write a modem message and test the resulting mqtt output.  The state machine inside the program is running during all of this, so a sequence of messages can also be sent and the results tested.
Unit testing is still undoubtedly the way to go as it is much more precise and focused.  But there have been times that I would have liked to been able to test in this fashion since I am often reverse engineering from insteon messages.
At the moment, there are only two tests performed here.
=> Add Platform for Integration Testing

HISTORY.md, insteon_mqtt/Modem.py, insteon_mqtt/Protocol.py, insteon_mqtt/cmd_line/device.py, insteon_mqtt/cmd_line/util.py, insteon_mqtt/db/Device.py, insteon_mqtt/db/Modem.py, insteon_mqtt/device/Base.py, insteon_mqtt/device/BatterySensor.py, insteon_mqtt/device/FanLinc.py, insteon_mqtt/handler/Base.py, insteon_mqtt/handler/ModemDbModify.py
Warning messages will be outputted in the MQTT messages and the command line, so they should be true warnings that we expect all users to see.
Some of our warnings were more suited as info.
Also improved the text of a few warnings.
Finally increased the command time out now that we have potentially long timeouts on db_get.
=> Tweak Logging Levels and Messages

HISTORY.md, insteon_mqtt/CommandSeq.py, insteon_mqtt/Modem.py, insteon_mqtt/db/Device.py, insteon_mqtt/device/Base.py, insteon_mqtt/device/BatterySensor.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/EZIO4O.py, insteon_mqtt/device/FanLinc.py, insteon_mqtt/device/IOLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Leak.py, insteon_mqtt/device/Motion.py, insteon_mqtt/device/Outlet.py, insteon_mqtt/device/Remote.py, insteon_mqtt/device/SmokeBridge.py, insteon_mqtt/device/Switch.py, insteon_mqtt/device/Thermostat.py, tests/test_Scenes.py
Reading nested command sequences out of a log was becoming a bit tedious.  This just adds a name to the log to try and make it a bit easier.
=> Add Name to Command Sequence Log

insteon_mqtt/Modem.py, insteon_mqtt/db/Modem.py, insteon_mqtt/handler/ModemDbModify.py, insteon_mqtt/handler/ModemDbSearch.py, insteon_mqtt/handler/__init__.py, insteon_mqtt/message/OutAllLinkUpdate.py, tests/db/test_Modem.py, tests/handler/test_ModemDbModify.py, tests/handler/test_ModemDbSearch.py, tests/util/helpers/main.py
So this is pretty cool.  I have reworked the Modem delete/add/modify routines so that they no longer care or require a refresh of the modem database.  This means things like pair, sync, and adding links should no longer fail because the Modem db is out of date.
In short, if you try and add a link that already exists, the modem will return a nak.  At which point we retry the action as an update instead.  The same is true if you try to update a link that doesn't exist.  The delete is a little more complicated and requires us to search the database first, but we can search specifically for these links.  
The cool thing is that this all happens in less than a second, so it isn't even noticable to users.
The only real need to refresh the modem db now is if you want to run sync to delete …
=> Remove Need to Refresh Modem Database

HISTORY.md, config.yaml, docs/mqtt.md, insteon_mqtt/cmd_line/device.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/device/BatterySensor.py, insteon_mqtt/device/Motion.py, insteon_mqtt/handler/Base.py, tests/cmd_line/test_device.py, tests/device/test_BatterySensorDev.py, tests/device/test_MotionDev.py, tests/util/helpers/main.py
The 2842 Motion Sensor can be queried for its battery voltage.  This is helpful, because I use Li-Ion batteries in these devices and their initial voltage is below what is deemed a low battery, so I never get low battery warnings from these devices.
This adds a feature allowing the user to select what a low voltage is, and then queries the battery voltage in the same way the Remote works.
I also removed retries on Battery devices for messages sent in response to the device being awake.  If the first message doesn't make it, the device will be asleep by the time a retry is done.  This does not apply when a device is manually marked awake.
I still new to write the unit tests.  But this is working on my setup.
=> Add 2842 Motion Sensor Battery Request; No Retries for Battery Devices when Briefly Awake

HISTORY.md, insteon_mqtt/Protocol.py, insteon_mqtt/device/Base.py, insteon_mqtt/handler/Broadcast.py, insteon_mqtt/log.py, insteon_mqtt/message/Flags.py, tests/handler/test_Broadcast.py, tests/test_Protocol.py
This pauses sending any messages after receiving a broadcast.  The pause length is calculated based on the known number of responders to which the device will be sending cleanup messages to.  If a cleanup report is received, then the broadcast sequence is finished and the pause is removed if any time is still remaining.
It also adds some reporting on receiving cleanup reports that have failures.  
Milliseconds has been added to the logging times and wait_times are now reported as the ending time instead of seconds to make debugging easier.
Unit tests are updated and this works on my end.
=> Add Pause After Broadcast Received

insteon_mqtt/db/Device.py, insteon_mqtt/db/DeviceModifyManagerI1.py, insteon_mqtt/db/Modem.py, insteon_mqtt/handler/DeviceDbModify.py, insteon_mqtt/handler/DeviceRefresh.py, tests/db/test_Device.py, tests/db/test_Modem.py
This changes the `set_delta` function to `increment_delta`.  Increment is really what was needed, plus this way it gracefully handles a delta of None for example if a user used refresh=False.  Unit tests included.
I also changed the clear function so that it does not delete the db file, but merely clears the entry lists and associated values.  Most importantly it leaves the meta dictionary intact.  So IOLincs will function properly after a refresh, and user settings such as battery level will not be erased.
Partially Fixes #292
Fixes #243
=> Minor Database Handling Fixes

config.yaml, insteon_mqtt/device/Base.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/mqtt/Dimmer.py, insteon_mqtt/mqtt/KeypadLinc.py, tests/device/test_DimmerDev.py, tests/device/test_KeypadLincDev.py, tests/mqtt/test_Dimmer.py, tests/mqtt/test_KeypadLinc.py
Improve on-level handling for dimmers & related devices
- Store default on-level in DB metadata when set-flags commmand succeeds.
- Use stored default on-level to determine new level when receiving "on" broadcast messages.
- Use stored default on-level to handle MQTT messages with unspecified brightness value.
- Note: Previous behavior for handling MQTT messages with unspecified brightness value will remain for existing users, unless config is updated as shown in example config.yaml file).
**Tests performed:**
* Some unrelated tests failed on my system (both before and after these changes were applied).  Old Python version might be to blame.
- Using an i2cs plug-in dimmer module and a KeypadLinc dimmer module:
- Pressed physical on button several times.  Confirmed that brightness as …
=> Improve on-level handling for dimmers & related devices

docs/mqtt.md, insteon_mqtt/db/Device.py, insteon_mqtt/db/Modem.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Outlet.py, insteon_mqtt/device/Switch.py, tests/device/test_DimmerDev.py, tests/device/test_KeypadLincDev.py, tests/device/test_OutletDev.py, tests/device/test_SwitchDev.py
This is primarily the work of @tommycw1 from #297.  This fixes #294.
This unbounds the backlight setting.  As @tommycw1 points out, values below the stated value in the documentation seem to work.  How low each device goes seems to vary, I have added documentation to help users.  All devices seem to have an upper limit at 0x7F.  But they all treat values above this as max.  So I have removed the bounding as it is unnecessary.
This also merges the backlight on/off command into the level command.  Setting the backlight to 0x00 will turn it off, and any other value will turn it on.
Tested on:
=> Unbound Backlight Brightness; Turn Backlight Off at 0x00

.github/workflows/python-app.yml, CHANGELOG.md, config.yaml, insteon_mqtt/Modem.py, insteon_mqtt/db/Modem.py, insteon_mqtt/handler/ModemInfo.py, insteon_mqtt/handler/__init__.py, insteon_mqtt/message/OutModemInfo.py, insteon_mqtt/message/__init__.py, tests/handler/test_ModemInfo.py, tests/message/test_OutModemInfo.py, tests/test_Integration.py, tests/test_Modem.py, tests/util/helpers/main.py
This will check the modem address on startup:
If no address is specified in the config file:
1. It will use the address obtained from the modem; OR
2. Fail and exit if no address is obtained.
If an address is specified in config:
1. If the returned address is the same, nothing
2. If the returned address is different, an error is reported,
and things will continue using the address in the config.
Closes #266
=> Check the Modem Address on Startup

CHANGELOG.md, insteon_mqtt/Protocol.py, insteon_mqtt/network/Hub.py, insteon_mqtt/network/Serial.py, tests/message/test_Timed.py, tests/network/test_Hub.py, tests/network/test_Serial.py
The write time was previously a timestamp that became fixed as
soon as the protocol wrote it to the Serial or Hub object.  The
Serial or Hub object would then sit on the message until that
time.
This design overlooked the possibility that the next write time
could change after the protcol sent the message to the Serial or
Hub.  This can happen if another message arrives, and the wait
time needs to be extended, or if a Link Cleanup report arrives
which could decrease the wait time.  This likely didn't cause
many errors, but wasn't quite right.
Now the write time is passed as a function which returns the
dynamic write time, so that the Serial and Hub ge the most up to
date calculation.
=> Change Next Write Time Passed to Serial or Hub to be Dynamic

CHANGELOG.md, insteon_mqtt/mqtt/Dimmer.py, insteon_mqtt/mqtt/EZIO4O.py, insteon_mqtt/mqtt/FanLinc.py, insteon_mqtt/mqtt/IOLinc.py, insteon_mqtt/mqtt/KeypadLinc.py, insteon_mqtt/mqtt/Modem.py, insteon_mqtt/mqtt/MsgTemplate.py, insteon_mqtt/mqtt/Outlet.py, insteon_mqtt/mqtt/Switch.py, insteon_mqtt/mqtt/Thermostat.py, tests/mqtt/test_MsgTemplate.py
If a user sends `'ON'` to a level topic expecting to receive a json payload like `{"state": "on","brightness":255}` they currently get the following errors in their log
```
2021-01-03 15:25:42.882 ERROR MsgTemplate: Error rendering template '{ "cmd" : "{{json.state.lower()}}",
"level" : {% if json.brightness is defined %}
{{json.brightness}}
{% else %}
255
{% endif %} }
' with data: {'value': 'ON', 'json': None}
Traceback (most recent call last):
File "/home/krkeegan/projects/insteon-mqtt/insteon_mqtt/mqtt/MsgTemplate.py", line 200, in _render
return template.render(data)
File "/home/krkeegan/projects/insteon-mqtt/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File …
```
=> Improve Error Reporting for Bad MQTT Templating

insteon_mqtt/mqtt/Mqtt.py
This fixes a bug introduced by #303.  Now that the startup is broken into parts, the MQTT link is established on a different turn through the loop than when all the devices are added.
=> Subscribe to Topics on New Device

CHANGELOG.md, docs/CONTRIBUTING.md, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/EZIO4O.py, insteon_mqtt/device/IOLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Motion.py, insteon_mqtt/device/Outlet.py, insteon_mqtt/device/Switch.py, tests/device/test_IOLincDev.py
Exceptions only show up in the LOG.  UI, Error, and Warning are sent out to the user UI.  I will add some suggestions on logging to the developer instructions.
There was no need to raise an exception here, plus without a LOG message, the user doesn't get very helpful instructions.
Previous:
```
Commanding dimmer device 12.29.84 (lamp2) cmd=set_flags                                                                 
ERROR: Error running command set_flags on device 12.29.84 (lamp2) 
```
Now:
```
Commanding dimmer device 12.29.84 (lamp2) cmd=set_flags                                                                 
ERROR: Unknown Dimmer flags input: {'on-level'}.                                                                         
Valid flags are: {'ramp_rate', 'on_level', 'backlight'} …
```
=> Improve UI Error on Unknown Flags in Set Flags

insteon_mqtt/mqtt/Mqtt.py, insteon_mqtt/network/Mqtt.py, tests/test_Integration.py
The return from network/mqtt.connect() does not describe whether the MQTT connection has been established.  This uses the on_connect callback instead.  The subscribe calls will only be made after on_connect signals a valid connection.
This Closes #312
This was a much easier fix than I expected.
=> MQTT Subscribe Only After MQTT Connect Callback

CHANGELOG.md, insteon_mqtt/Scenes.py, insteon_mqtt/db/Modem.py, tests/test_Scenes.py
=> Enable Adding Multiple Modem Controlled Scenes at Once

insteon_mqtt/Scenes.py, tests/test_Scenes.py
Related to #321
A further latent bug in the functionality that I had not thought of.
=> Remove Modem Groups in Scenes File from Empty Group List

insteon_mqtt/handler/Base.py, insteon_mqtt/handler/BroadcastCmdResponse.py, insteon_mqtt/handler/DeviceDbGet.py, insteon_mqtt/handler/DeviceDbModify.py, insteon_mqtt/handler/DeviceRefresh.py, insteon_mqtt/handler/ExtendedCmdResponse.py, insteon_mqtt/handler/ModemDbGet.py, insteon_mqtt/handler/ModemDbModify.py, insteon_mqtt/handler/ModemDbSearch.py, insteon_mqtt/handler/ModemInfo.py, insteon_mqtt/handler/ModemLinkStart.py, insteon_mqtt/handler/ModemScene.py, insteon_mqtt/handler/StandardCmd.py, insteon_mqtt/handler/StandardCmdNAK.py, tests/handler/test_BroadcastCmdResponse.py, tests/handler/test_DeviceDbGet.py, tests/handler/test_ExtendedCmdResponse.py, tests/handler/test_ModemDbGet.py, tests/handler/test_ModemDbModify.py, tests/handler/test_ModemDbSearch.py, tests/handler/test_ModemInfo.py, tests/handler/test_StandardCmd.py, tests/test_Integration.py
This fixes #260 
This adds two flags to all handlers
- `_PLM_sent` is false by default and is marked true when `sending_message()` is called.
- `_PLM_ACK` is initially false and is marked true whenever a matching PLM Ack is received after _PLM_sent is true.
All handlers were updated with logic that requires `_PLM_sent` to be true before handing any message, they return `Msg.UNKNOWN` otherwise.  Handlers that process messages beyond the simple PLM ACK message require receiving a PLM Ack before that further processing can occur.  Again, these messages will return `Msg.UNKNOWN` prior to that.
=> Force Checking of Msg Sent and PLM Ack

insteon_mqtt/device/BatterySensor.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/EZIO4O.py, insteon_mqtt/device/IOLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Outlet.py, insteon_mqtt/device/Switch.py, insteon_mqtt/device/functions/Set.py, insteon_mqtt/device/functions/SetAndState.py, insteon_mqtt/device/functions/State.py, insteon_mqtt/device/functions/__init__.py, insteon_mqtt/mqtt/Dimmer.py, insteon_mqtt/mqtt/IOLinc.py, insteon_mqtt/mqtt/KeypadLinc.py, insteon_mqtt/mqtt/topic/SetTopic.py, insteon_mqtt/mqtt/topic/StateTopic.py, tests/device/test_BatterySensorDev.py, tests/device/test_DimmerDev.py, tests/device/test_IOLincDev.py, tests/device/test_KeypadLincDev.py, tests/device/test_MotionDev.py, tests/device/test_OutletDev.py, tests/device/test_SwitchDev.py, tests/mqtt/test_IOLincMqtt.py, tests/mqtt/test_KeypadLinc.py, tests/mqtt/test_KeypadLinc_sw.py
Continuing the process of condensing everything.  This moves the following functions which were largely duplicated into a single location:
- On
- Off
- Set
- Handle_Ack - The callback for the above functions
- _Set_State - Called by Handle_Ack (among others).  Used to cache the device state and emit the data to the state topic.  It was previously named all sorts of things in various files.
Again, this probably adds support to the "reason" attribute in some places where it was not previously enabled.
There are still a few more things that can be cleaned up.  The set-flags regime is looking ripe for a cleanup as well.
=> Refactor Device Classes - Set, On, Off, Set_State, Handle_Ack Functions

insteon_mqtt/device/Base.py, insteon_mqtt/device/BatterySensor.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/IOLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/Leak.py, insteon_mqtt/device/Motion.py, insteon_mqtt/device/Outlet.py, insteon_mqtt/device/Remote.py, insteon_mqtt/device/SmokeBridge.py, insteon_mqtt/device/Switch.py, insteon_mqtt/device/Thermostat.py, insteon_mqtt/handler/Broadcast.py, tests/device/test_BatterySensorDev.py, tests/device/test_LeakDev.py, tests/device/test_MotionDev.py, tests/handler/test_Broadcast.py
After fixing #283, there is no longer a need to pass these messages on to the callbacks.
- Not all devices send these messages
- Some devices allow users to disable these messages
- The messages do not contain any valid ON/OFF data that the callback can process
- Removing them simplifies the callback code.
- We shouldn't expect to handle such a low level messaging at the device level
=> Remove Link_Cleanup_Report from Broadcast Callbacks

insteon_mqtt/network/Mqtt.py
When an explicit MQTT client ID is configured, the previously-created MQTT client gets reinitialised so that it will be used. This results in the previously-configured callback functions being lost.
A new setup_client function has been added so that both code paths will configure the MQTT client the same way.
Closes #350.
=> Refactor MQTT client configuration to ensure consistency

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Add github templates for Issues and Pull Requests.  I tried to keep them concise but complete.  These should help things go a little more smoothly and will encourage me to be more thoughtful in my documentation and notification of changes.
=> Add Github Templates for Issues and PRs

CHANGELOG.md, insteon_mqtt/handler/BroadcastCmdResponse.py, tests/handler/test_BroadcastCmdResponse.py
Checks that a device ack is received before processing the
broadcast response.
Fixes #335
=> Check for Device Ack in BroadcastCmdResponse; Add Unit Tests

CHANGELOG.md, docs/mqtt.md, insteon_mqtt/Modem.py, insteon_mqtt/handler/ModemGetFlags.py, insteon_mqtt/handler/__init__.py, insteon_mqtt/message/OutGetModemFlags.py, insteon_mqtt/message/__init__.py, tests/handler/test_ModemGetFlags.py, tests/message/test_OutGetModemFlags.py
Adds support for the `get_flags` command on the modem.  The value is only outputted to the log and the UI, it is not saved.
This may be helpful for debugging obscure modem issues, or might be useful in the future.
- This PR is related to issue: #351
=> Add Get_Flags Function to Modem

insteon_mqtt/device/base/DimmerBase.py, insteon_mqtt/device/base/ResponderBase.py, tests/device/test_IOLincDev.py
Moves handle_refresh with level support from ResponderBase to DimmerBase.  This was a mistake I made in #334.  There is no affect on the end user, this is only a change that alters how the code appears to a developer.
=> Move Handle_Refresh with Level from ResponderBase to DimmerBase

CHANGELOG.md, insteon_mqtt/db/Modem.py, insteon_mqtt/handler/ModemDbModify.py, insteon_mqtt/message/DbFlags.py, insteon_mqtt/message/OutAllLinkUpdate.py, tests/db/test_Modem.py, tests/handler/test_ModemDbModify.py
Contrary to the Insteon Specification, it appears the DB Flags can be used in the Delete command.  While using 0x00 for the flags worked in most circumstances, it appears that in some cases for an unknown reason the Delete command would fail on USB Dongle style PLMs.  It is possible that the command was also failing on other PLM styles as well and was not noticed or reported.
Using the DB_Flags is a net win, 1) it simplifies the delete functionality significantly and 2) it seems to solve the problem wherein entries could not be deleted. 
This change removes the complicated Command_Seq wherein the modem first had to be searched for records to delete, the records were deleted and any necessary restored records were restored.
Now, the delete function simply takes an entry and deletes it.  If …
=> Simplify Modem DB Delete by Using DB_Flags

CHANGELOG.md, config-example.yaml, docs/auto_start.md, docs/quick_start.md, hassio/entrypoint.sh, tests/test_Integration.py, tests/test_Modem.py
Home Assistant now supports defining the supervisor config in yaml form.  Which is causing it to read our config.yaml file as a Supervisor config and throwing all sorts of warnings.
This renames the included config file, which also has the benefit of making it more clear to users that they need to modify the
file before using it.
- This PR fixes or closes issue: fixes #362
=> Rename Config.yaml -> Config-Example.yaml

CHANGELOG.md, insteon_mqtt/device/KeypadLinc.py, tests/device/test_KeypadLincDev_sw.py
Extend decode_on_level for keypadlincs to insert the proper group number instead of the default None.
Fixes a glitch where the switch variety of Keypadlincs were unable to render the proper topic without the button value.
Also adds unit tests.
- This PR fixes or closes issue: fixes at least one bug in #366
=> Add Button to Decode_On_Level;  Add Unit Tests

CHANGELOG.md, config-example.yaml, insteon_mqtt/network/Mqtt.py
Logging of the Paho Client was previously available through a somewhat hidden log level of 5.  This means that Paho Error messages were only visible in the log if the logging level was at 5 or lower.
This change moves all Paho Client log messages into the log at their defined level.  So if a user has Error messages enabled
Paho Error messages will appear in the log.
The one exception, is that the Paho Client logs ping messages at the debug level, which is a little verbose I think for our needs.
So all logging of ping messages have been moved to level 5.
Added notes to the config example about the level 5 logging level.
- This PR is related to issue: #366
=> Move Paho Client Log Messages into Log at Same Level

docs/config_extra.md, docs/configuration.md, insteon_mqtt/device/BatterySensor.py, insteon_mqtt/device/Dimmer.py, insteon_mqtt/device/EZIO4O.py, insteon_mqtt/device/FanLinc.py, insteon_mqtt/device/HiddenDoor.py, insteon_mqtt/device/IOLinc.py, insteon_mqtt/device/KeypadLinc.py, insteon_mqtt/device/KeypadLincDimmer.py, insteon_mqtt/device/Leak.py, insteon_mqtt/device/Motion.py, insteon_mqtt/device/Outlet.py, insteon_mqtt/device/Remote.py, insteon_mqtt/device/SmokeBridge.py, insteon_mqtt/device/Switch.py, insteon_mqtt/device/Thermostat.py, insteon_mqtt/device/base/Base.py, insteon_mqtt/device/base/DimmerBase.py, insteon_mqtt/device/base/ResponderBase.py, insteon_mqtt/device/functions/Backlight.py, insteon_mqtt/device/functions/ManualCtrl.py, insteon_mqtt/device/functions/Scene.py, tests/device/base/test_BaseDev.py, tests/device/test_RemoteDev.py, tests/mqtt/test_Remote.py, tests/mqtt/test_config.py, tests/test_Scenes.py
This adds the ability to define extra device specific configuration settings in the `config.yaml` file.  At the moment, the only additional setting that is used is the `min_hops` setting.  This sets the minimum hop count that is set for the `max_hops` flag in outgoing messages to this particular device.
Device specific configuration is defined using the following format:
```yaml
insteon:
devices:
switch:
- aa.bb.cc: lamp1
extra_config: 1
- 11.22.33: lamp2
```
Each config_extra key and value is added to a dict that is available as the attribute `config_extra` for each device.  It is up to the device to decide how to handle this.
Due to this format in yaml, there is one major limitation:
> extra_config keys cannot be interpreted as a device address.  As such, the key needs to be longer than …
=> Add Config_Extra Option; Add Min_Hops as First Setting

config-example.yaml, docs/mqtt.md
This is not specifically a breaking change in InsteonMQTT, but fixing a breaking change in HomeAssistant.
Suggested setup has changed because HomeAssistant now (2021.4.0) uses percentages for the fan speed instead of low/med/high.
Thanks @Juggler00 for the fix
- This PR closes: #377
=> Update Example Config for Fan in HomeAssistant

insteon_mqtt/device/base/Base.py, tests/db/test_DeviceEntry.py, tests/db/test_ModemEntry.py, tests/device/base/test_BaseDev.py, tests/test_Scenes.py
Adds an attribute to the base device class `name_user_case` which contains the name of the device in the case as entered by the user.  To be used for setting the `name` in the discovery payload.
I am starting the process of adding discovery support.  This may take a little bit of time, but shouldn't be too bad.  Rather than keep my commits hidden, I thought it would be better to create a new branch and frequently merge PRs to that branch.  I will probably merge these PRs rather quickly, but if you see errors or have comments, please let me know.  They can be addressed in further PRs.
Once the Discovery branch is complete, it can be merged into dev.
=> Store Name in Case as Entered by User

config-example.yaml, insteon_mqtt/mqtt/Dimmer.py, insteon_mqtt/mqtt/Mqtt.py, insteon_mqtt/mqtt/topic/BaseTopic.py, insteon_mqtt/mqtt/topic/DiscoveryTopic.py, insteon_mqtt/mqtt/topic/ManualTopic.py, insteon_mqtt/mqtt/topic/SceneTopic.py, insteon_mqtt/mqtt/topic/SetTopic.py, insteon_mqtt/mqtt/topic/StateTopic.py, insteon_mqtt/mqtt/topic/__init__.py
This is a functioning basic implementation of the Discovery feature.  It lacks lots of documentation, and is only implemented on Dimmers.  The idea is this:
1. There are some global yaml settings for discovery such as `discovery_topic_base` and `discovery_ha_status`
2. There is a global setting for `device_info_template` that allows the user to define a device template that can be reused as a variable in the discovery templates.  @schirner had implemented something like this, and I agree this is very handy.  This is likely to be reused in every template.
3. By default each device class will look in it's subkey under the `mqtt` key in the config.yaml file for the discovery templates.  So dimmers look to `mqtt->dimmer` by default.
4. Inside this class, a `discovery_entities` key is defined. …
=> Skeleton of Discovery Implementation

config-example.yaml, docs/config_extra.md, docs/discovery.md, insteon_mqtt/mqtt/Dimmer.py, insteon_mqtt/mqtt/Mqtt.py, insteon_mqtt/mqtt/topic/DiscoveryTopic.py
This adds a bunch of documentation for Discovery, including the user facing documentation.
I also added a few more variables for templating and tweaked some of them to improve their appearance.
The default `device_info_template` has been improved to provide nice fall backs for decreasing knowledge about a device.
I also streamlined some of the code around initialization.
- This PR is related to issue: #128
=> Discovery Documentation; Additional Variables and Tweaks

config-example.yaml, docs/discovery.md, insteon_mqtt/Modem.py, insteon_mqtt/mqtt/BatterySensor.py, insteon_mqtt/mqtt/Dimmer.py, insteon_mqtt/mqtt/EZIO4O.py, insteon_mqtt/mqtt/FanLinc.py, insteon_mqtt/mqtt/HiddenDoor.py, insteon_mqtt/mqtt/IOLinc.py, insteon_mqtt/mqtt/KeypadLinc.py, insteon_mqtt/mqtt/KeypadLincDimmer.py, insteon_mqtt/mqtt/Leak.py, insteon_mqtt/mqtt/Modem.py, insteon_mqtt/mqtt/Motion.py, insteon_mqtt/mqtt/Outlet.py, insteon_mqtt/mqtt/Remote.py, insteon_mqtt/mqtt/SmokeBridge.py, insteon_mqtt/mqtt/Switch.py, insteon_mqtt/mqtt/Thermostat.py, insteon_mqtt/mqtt/topic/BaseTopic.py, insteon_mqtt/mqtt/topic/DiscoveryTopic.py, insteon_mqtt/mqtt/topic/ManualTopic.py, insteon_mqtt/mqtt/topic/SceneTopic.py, insteon_mqtt/mqtt/topic/SetTopic.py, insteon_mqtt/mqtt/topic/StateTopic.py
This adds the discovery platform support to the devices.  ~I still need to finish the KPL, outlets, io_lincs, and ezio4.  But this is a lot of code, so I am pushing it early.  I will likely push support for the other 4 devices tomorrow.~ Done.
So far, this seems to be working reasonably well.  The biggest time suck is getting the ideal config template for HomeAssistant for each device.
The Remotes and KPL discovery entries are going to be verbose.  I struggled over the weekend thinking about ways in which the entities for each button could be duplicated from a single definition.  I was not able to come up with one that didn't make the code overly complex or the definition for the user overly awkward.
I also made some good updates to the documentation when I discover issues that users are …
=> Add Discovery Support to All Devices

config-example.yaml, insteon_mqtt/mqtt/Modem.py, insteon_mqtt/mqtt/Mqtt.py, insteon_mqtt/mqtt/topic/DiscoveryTopic.py, tests/mqtt/test_BatterySensor.py, tests/mqtt/test_Dimmer.py, tests/mqtt/test_EZIO4O.py, tests/mqtt/test_FanLinc.py, tests/mqtt/test_IOLincMqtt.py, tests/mqtt/test_KeypadLinc.py, tests/mqtt/test_KeypadLinc_sw.py, tests/mqtt/test_Leak.py, tests/mqtt/test_Modem.py, tests/mqtt/test_Motion.py, tests/mqtt/test_Mqtt.py, tests/mqtt/test_Outlet.py, tests/mqtt/test_Remote.py, tests/mqtt/test_SmokeBridge.py, tests/mqtt/test_Switch.py, tests/mqtt/test_ThermostatMqtt.py, tests/mqtt/topic/test_DiscoveryTopic.py, tests/util/helpers/main.py
This adds unit tests to the base Mqtt and the DiscoveryTopic classes covering the discovery code.
~I have also added some unit tests to the individual device classes but I have a little ways to go on them.~ Done
- This PR is related to issue: #128
=> Add Unit Tests to Discovery Platform

config-example.yaml, insteon_mqtt/mqtt/Modem.py, insteon_mqtt/mqtt/topic/DiscoveryTopic.py, tests/mqtt/test_Modem.py, tests/mqtt/topic/test_DiscoveryTopic.py
These are a few small fixes to the Discovery platform that I found while setting it up.
1. HomeAssistant does not allow periods in the node_id or the object_id in the topic.  They only allow a small set of characters.  This does not carry through to things in the payload.  Solved this by changing any out of bounds characters to underscore.
2. The logic in loading the modem discovery topics was flawed.  This fixes it.
3. Some other small fixes to the suggested config.
=> Discovery Tweaks After Initial Usage

docs/initializing.md, docs/mqtt.md, insteon_mqtt/Modem.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/cmd_line/modem.py, tests/cmd_line/test_modem.py
The "skip battery devices" option was removed from the `refresh_all` and `get_engine_all` commands as it is no longer necessary.  Messages sent to battery devices are automatically queued for the next time they wake up.  Removing this simplifies things for users.
Adds `join_all` and `pair_all` commands.  Self explanatory.
- This PR fixes or closes issue: closes #380
=> Add Join_All and Pair_All Commands; Remove Battery Option

insteon_mqtt/handler/DeviceRefresh.py
We were only saving to the variable and not pushing to the file which could cause a false `out-of-date` response after a restart.
This calls save after a successful refresh a simple one-liner.
=> Save DB Delta to File on Refresh Complete

config-example.yaml, insteon_mqtt/mqtt/topic/BaseTopic.py, tests/mqtt/test_BatterySensor.py, tests/mqtt/test_Dimmer.py, tests/mqtt/test_EZIO4O.py, tests/mqtt/test_FanLinc.py, tests/mqtt/test_IOLincMqtt.py, tests/mqtt/test_KeypadLinc.py, tests/mqtt/test_KeypadLinc_sw.py, tests/mqtt/test_Leak.py, tests/mqtt/test_Modem.py, tests/mqtt/test_Motion.py, tests/mqtt/test_Outlet.py, tests/mqtt/test_Remote.py, tests/mqtt/test_Switch.py
This adds the templating variable `{{timestamp}}` to all templates.  It outputs the current timestamp.
I am using this as an attribute in addition to `reason` in automation conditions.  It is helpful in preventing automations from triggering on a restart of HA or the MQTT Broker when using the retain flag.
A simple check in HA is to test if the timestamp of the state change is within the last 5 seconds (could certainly be shorter). If it is not, then this message is likely being redelivered because of the retain flag, and I can avoid re-triggering an automation.
=> Add Timestamp as a Templating Variable

insteon_mqtt/device/FanLinc.py
I spent a small amount of time looking into the error I reported in #398 and found the `responder_groups`  list doesn't appear to be updated correctly for fan lincs.
This adds group 2 into the list of responder groups for fanlinc devices
I'm not familiar enough with the code to know if this is an appropriate change; however, it seemed like it would help move me past the exception I'm running into.
- This PR is related to issue: #398
Do you have examples you can point me to that demonstrate how to test this type of change?
=> add group 2 to fanlinc responders group

insteon_mqtt/device/FanLinc.py
Adds support for on and off commands for the fanlinc.
Expands on PR #399.
- This PR fixes or closes issue: fixes #398
=> Add On Off Command Support to Fan Group on FanLinc

insteon_mqtt/config.py, insteon_mqtt/schemas/config-schema.yaml, tests/test_config.py
Allows for domain names to be used for the broker and hub addresses.
New tests added to catch this in the future.
- This PR fixes or closes issue: fixes #403
=> Allow Domain Names for Broker and Hub; Remove IP Test

build-docker.sh
Fixes the build process to work more reliably by building the docker images using the local docker instance instead of the docker-in-docker design used by HomeAssistant.
- This PR fixes or closes issue: fixes #375
=> Run Docker Build on Local Docker Instance

.gitignore
This just adds the file `01.02.03.json` and folder `data` created by the tests into the gitignore
the only failing test is the config test that references `use_dns.yaml`
=> add files created by tests to gitignore

hassio/entrypoint.sh
This fixes the initial config setup on a new install (it current bails because `/opt/insteon-mqtt/config.yaml` does not exist)
=> fix issue with hassio initial config setup

docs/mqtt.md, insteon_mqtt/device/base/DimmerBase.py, tests/device/test_DimmerDev.py
This exposes the ability to configure the "Resume Dim" operating flag. It configures the device to use the previous on level instead of the value of the `on_level` flag as the default level for a normal on command.
I'm unfamiliar with the code base, so still going through and making sure I've updated documentation where appropriate. I'm also unsure how to add unit tests for a change like this.
The command values were pulled from http://cache.insteon.com/pdf/INSTEON_Command_Tables_20070925a.pdf
=> allow configuring the resume dim operating flag

docs/mqtt.md, insteon_mqtt/cmd_line/device.py, insteon_mqtt/cmd_line/main.py, insteon_mqtt/device/base/Base.py, tests/device/base/test_BaseDev.py
This arose while debugging #411 (and messing around with the other commands I found in the command tables). Essentially I found it a lot easier to debug the actual commands when I had the ability to send raw insteon commands through mqtt
I don't think this is a common use case, and there's some cleanup that needs to happen if this were desired (tests, docs, etc); but am happy to work through those if this is would be desired
=> allow sending raw commands to devices

insteon_mqtt/data/config-schema.yaml
A simple one-liner.
If a user mistakenly puts extra keys in a discovery class the
current error looks like:
```yaml
mqtt:
kpl_six:
btn_on_off_payload:
- must be of dict type
```
This updates the schema so that the error now looks like:
```yaml
mqtt:
kpl_six:
btn_on_off_payload:
- unknown field
```
A slight improvement in wording.
- This PR is related to issue: #418
=> Better Error Report When Unknown Fields are in Discovery Class

insteon_mqtt/data/config-base.yaml, tests/network/test_Hub.py, tests/test_Integration.py
If merged as part of 1.0.0 nothing will break.  Users with config files prior to this will have settings that override these changes.
Changes the default payload of the state topics and a few others to use JSON payloads with additional attributes such as `reason`, `mode`, `timestamp`, and any others that are available.
Also updates the default discovery entities for HomeAssistant so that these attributes are exposed to HomeAssistant by default.
Basically, this exposes more of the functionality in InsteonMQTT to the user by default.
This should be merged with 1.0.0.
=> Convert Default State Payloads to JSON; Add Attributes by Default

tests/mqtt/test_KeypadLinc.py
Fixes a broken KPL Unit Test.  Not sure how this has slipped through for so long.  Was there a change in how python handles `int('')` that I missed?
=> Fix KPL Unit Test; Only Add Level if Defined

insteon_mqtt/device/base/Base.py, insteon_mqtt/device/base/DimmerBase.py, tests/device/test_DimmerDev.py
Enables the resume_dim flag for non i2cs devices
- This PR fixes or closes issue: fixes #415 
I only have i2cs devices, so will need help verifying this works properly for non i2cs devices :-)
=> Resume dim for non i2cs devices

CHANGELOG.md, config-example.yaml, docs/hub.md
Adds documentation for the 2242-222 (~2012) hubs.  Thanks @tbirdsaw.
- This PR closes issue: fixes #428
=> Add Documentation for 2242-222 Hubs (~2012)

docs/HA_Addon_Instructions.md, docs/HA_yaml_config.md, insteon_mqtt/data/config-base.yaml
This adds a new documentation page with instructions for manually configuring HomeAssistant entities using yaml.  The page provides example yaml configurations that should work for all device types.
Any similar instructions contained in the config_base.yaml were removed.
The instructions for installing on Home Assistant were also updated to recommend using the Discovery Platform.
Comments in the config_base.yaml were also moved to be underneath there respective subkey.  This makes code folding of the comments possible.
- This PR is related to issue: #425
Note, no actual code was touched.  These are all comment or documentation changes.
=> Add Instructions for Home Assistant Yaml Config; Update HA Installation for Discovery

docs/HA_yaml_config.md, insteon_mqtt/data/config-base.yaml
Turns out HomeAssistant needs the min max values set, without them things can get weird.  This doesn't have any effect on anyone not using HomeAssistant.
Updated the default Discovery payload to provide the HA defaults for min and max temps.  Also updated the documentation of suggested HA configuration.
=> Add Min Max Values to Discovery and Suggested HA Config

config-example.yaml, insteon_mqtt/data/config-base.yaml, insteon_mqtt/data/config-schema.yaml, insteon_mqtt/network/Mqtt.py
This adds optional support for encryption of the connection to the MQTT broker.  It also includes an option to use certificates to authenticate the client.
=> Add Encryption Support to MQTT Broker Connection

insteon_mqtt/data/config-base.yaml
This change adds state_topic and state_value_template to the discovery information for the fan component of fanlinc devices.  Without these topics, Home Assistant treats the fan as always off.
- This PR fixes a problem where Home Assistant displays the state of fanlinc fans as "off" even though they are actually on.
- Tested by overriding discovery_entities in config.yaml and applying as custom discovery class.
- Four tests fail both on master and on my branch locally.  I assume this is just a problem with my environment.
- No new code added
- N/A
- N/A
=> Add fan state to fan_linc discovery info

insteon_mqtt/device/KeypadLinc.py, tests/device/test_KeypadLincDev.py
Written originally for #433, but it doesn't look like this is the problem.  Unit tests of the old and new code produce the same results.
Never the less, using is_on rather than level seems more clear for setting the led bits.
Added unit tests to catch if led bit setting is not happening.
- This PR is related to issue: #433
=> Tweak KPL LED Bit Process; Add Unit Tests

insteon_mqtt/data/config-base.yaml
I noticed that my heartbeat sensors associated with my leak sensors were displaying "invalid timestamp" in HomeAssistant.  I would swear that these worked previously and I am not sure when HA changed things.
This simply changes the default discovery template for the leak sensors to add a value template which converts our timestamp into an ISO8601 date string required by HomeAssistant.
=> Fix Heartbeat Timestamp Sensors in HomeAssistant Discovery

insteon_mqtt/data/config-base.yaml, insteon_mqtt/mqtt/Leak.py, tests/mqtt/test_Leak.py
The wrong topic string is being returned when the template variable `{{wet_dry_topic}}` for leak sensors.
I made a mistake with how I was adding the wet dry topic to the rendered topic map.  This fixes that error.
I fixed the unit tests to catch this error in the future.
There is one issue here.  We cannot specify a default topic string or payload string for the leak sensor in the code.  Because the wet_dry topic replaces the state_topic inherited from battery_sensor, the battery_sensor values will prevail if none are specified.  There is no elegant want to correct this.  The right answer would be to unify the config key values so that leak used state_topic and state_payload.  If future issues arise, we should consider that.
- This PR fixes or closes issue: #442
=> Fix Wet Topic for Leak Sensor

insteon_mqtt/cmd_line/util.py
This is basically just copied code from the MQTT network interface that already has support for encrypted connections.
Without this, if the user had specified an encrypted port number, the command line would hang and timeout because the command line client was never able to connect.
=> Add Support for Encrypted MQTT Connections to Command Line

docs/discovery.md, insteon_mqtt/data/config-base.yaml, insteon_mqtt/data/config-schema.yaml, insteon_mqtt/mqtt/Mqtt.py, insteon_mqtt/mqtt/topic/DiscoveryTopic.py, insteon_mqtt/network/Mqtt.py, tests/mqtt/test_Modem.py, tests/mqtt/test_Mqtt.py, tests/mqtt/topic/test_DiscoveryTopic.py, tests/util/helpers/network.py
Adds an availability topic, which is by default at `insteon/availability`.  This topic has been added to the default discovery templates.
This enables HomeAssistant to determine if InsteonMQTT is online or not and to represent the state of the devices appropriately.
- This PR fixes or closes issue: fixes #446
=> Add Availability Topic

insteon_mqtt/device/base/Base.py, insteon_mqtt/device/base/DimmerBase.py, insteon_mqtt/device/functions/Scene.py, tests/device/functions/test_Scene.py
If a level is specified in a scene command, it is saved.  If a broadcast message is received from a device within 5 seconds of calling the scene command, the level is set to the saved scene level.
- This PR fixes or closes issue: fixes #316
=> If Scene Level is Specified Set Device to Level on Receipt of Broadcast

insteon_mqtt/Modem.py, tests/test_Modem.py
This is a __significant__ bug fix.  Not sure how long this has been an issue.  I only noticed it when I had to replace a PLM.
When pairing a multigroup device such as a keypadlinc, remote, motion, ... The responder links for the secondary groups (not 0/1) were not being added to the modem.
This was happening because `_db_update` on the modem was treating the local_group as the scene group number for responder links.  Since all responder links on the modem have a local_group of `0x01` this essentially meant that only one responder link would be added to the modem per device since all responder links looked the same.
The solution is to use the remote_group as the scene group number on responder links.  This code is written properly for all other devices except the modem, so I just copied …
=> Use Remote Group When Adding Resp Link on Modem

insteon_mqtt/device/Motion.py, tests/device/test_MotionDev.py
On_Only and Night_Only are actually false on the device.  Looking back at my old notes, I captured this data before, but failed to pay attention to the bit value and was only focused on the position.
This is just a simple fix to invert those bits when setting them.
Tests were updated to catch this.
- This PR fixes or closes issue: fixes #462
=> Invert On_Only and Night_Only Bits on Motion Sensor

insteon_mqtt/cmd_line/argparse_ext.py, insteon_mqtt/cmd_line/main.py
A major cleanup of the helptext produced on the command line.
* Removed excess matter where possible
* Add description and pointer to command help
* Extend Argparse module to Enable Grouping Sub-Parsers
* Create groups for all commands to make them easier to find and read.
* Reorder Commands in a logical fashion
* Rewrite some help text
* Add Description to all Commands so that command help contains details about the command.
```
usage: insteon-mqtt [-h] [-v]
config.yaml
{start,refresh-all,sync-all,import-scenes-all,get-engine-all,join-all,pair-all,factory-reset,
get-devices,linking,join,refresh,get-flags,set-flags,get-engine,get-model,on,set,off,up,down,scene,
pair,db-add,db-delete,set-button-led,print-db,sync,import-scenes,awake,get-battery-voltage,
set-low-battery-voltage,raw-command} …
```
=> Overhaul of Commandline Help Output

insteon_mqtt/data/scenes-schema.yaml, tests/configs/scenes_empty.yaml, tests/test_config.py
This allows users to enable scene support and then import their
existing scenes from the Insteon network.
- This PR fixes or closes issue: fixes #482
=> Allow 'scenes.yaml' to be empty

hassio/webcli/app.py
Adds a newly required flag that allows Flask webserver to run.
As before, you will continue to get the following at the start of your log:
```
WebSocket transport not available. Install simple-websocket for improved performance.
Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
```
This is fine.  We are running a webserver for a single client behind the authentication of HomeAssistant and behind the ingress proxy.
=> Suppress Flask Runtime Error

docs/discovery.md, insteon_mqtt/data/config-base.yaml
Fixes the breaking change introduced in HomeAssistant 2023.8.0.  The changes should not affect any existing user, and only alter the default friendly names generated for entities.
Generally removes the `device_name` as a prefix in `entity name`.  For devices with only one entity, or for entities that provide the primary purpose of the device, the name is set to "" which causes HomeAssistant to use the `device_name` as the `entity_name`.  For all other entities, HomeAssistant will automatically prepend the `device_name` to the `entity_name`.
For a more detailed explanation on the HomeAssitant change see:
[HomeAssistant Entity Naming Guidelines](https://developers.home-assistant.io/docs/core/entity/#entity-naming),
[Change in MQTT Naming](https://github.com/home-assistant/core/pull/95159), …
=> Rework Entity Names in Discovery Template for HA >2023.8.0

insteon_mqtt/device/Switch.py, insteon_mqtt/device/base/ResponderBase.py, tests/device/test_SwitchDev.py
This change fixes a bug whereby switch scenes that are configured to turn the switch off (i.e. with data_1 == 0x00) would be marked as having turned the switch on in MQTT, despite the switch actually turning off.
- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Related to discussion: #338
**Note:** I wasn't sure if other device types that have on-off states (e.g. KeypadLinc, Outlet) behaved the same (as I don't have these devices), so this change only applies to the Switch device type.  Let me know if you know which other devices work this way and if you'd like me to add changes for them to this PR.
Confirmed no new flake8 errors, pylint errors, or code coverage gaps.  All tests passing.  Also, confirmed new test …
=> Fix switch state representation for scenes that turn switches off

insteon_mqtt/device/base/ResponderBase.py, tests/device/base/test_ResponderBase.py
Allows for the use of mode strings such as "instant", "fast", "normal" ... when calling the `on`, `off`, and `set` functions on a device.  This is necessary because the command line interface uses the `command` topic and not the `set` or `level` topics.  There is no sanitizing of the mode argument in the command topic and there really isn't a sensible way to add it there.
- This PR fixes or closes issue: fixes #512
=> Allow String Mode When Using On, Off, or Set Command

insteon_mqtt/device/Motion.py, tests/device/test_MotionDev.py
Theoretically this could be a breaking change if users are relying on the bad values.  But I don't think many people use this function, and this brings it inline with the expected value.
Flips the reported dusk/dawn values.  According to #511 this was backwards.  I was unable to get these messages to work on my sensors and sadly the tech documents for the motion sensor are silent about this feature.  But this report is backed up by documentation found here: https://wiki.indigodomo.com/doku.php?id=insteon_devices:sensors
- This PR fixes or closes issue: fixes #511
=> Reverse Dusk/Dawn Signal

insteon_mqtt/device/BatterySensor.py, tests/device/test_BatterySensorDev.py
This change fixes a bug whereby identical refresh requests may pile up in a non-awake device's send queue over time.  For example, I had an automation running at 15-minute intervals that would perform a refresh-all command.  Several days later, when I performed an "awake" command against a mini-remote device (2342-232), Insteon-MQTT tried to send several hundred refresh commands to the mini-remote.
This change avoids queuing more than one refresh command by replacing identical queued refresh commands with newly-received refresh commands (under the assumption that it might be more convenient to the user if the new command is still waiting for a response at the time the device is woken up).
Confirmed no new flake8 errors, pylint errors, or code coverage gaps. All tests passing. Also, …
=> Don't let refresh requests pile up while not awake

insteon_mqtt/db/Device.py, insteon_mqtt/db/DeviceScanManagerI2.py, insteon_mqtt/db/__init__.py, insteon_mqtt/handler/DeviceDbGet.py, insteon_mqtt/handler/DeviceRefresh.py, tests/db/test_DeviceScanManagerI2.py, tests/handler/test_DeviceDbGet.py, tests/handler/test_DeviceRefresh.py
Also, improve DeviceDbGet & DeviceRefresh test coverage.
Thanks for considering this PR!
This PR changes the DeviceRefresh handling so that, after attempting a bulk database download (with DeviceDbGet), if the database is incomplete, Insteon-MQTT will attempt to retrieve the missing DB entries one-by-one.
This feature was previously proposed by @krkeegan in [this message](https://github.com/TD22057/insteon-mqtt/issues/233#issuecomment-742697299) on #233:
> I thought about this a bit more. I am still of the mindset that the current system using the single request is preferable. However, I thought of a way to add in support for individual requests as a fallback. The process would look like:
> 
> 1. Perform the db get as we do currently. (at the start of this the cached db is emptied)
> 2. …
=> If not all DB records are received, try one-by-one

insteon_mqtt/cmd_line/util.py, insteon_mqtt/network/Mqtt.py, requirements.txt
Upgrades Paho Client to API Version 2, removed deprecation warning.  Relatively simple migration, not much to change, shouldn't be any user impact
- This PR fixes or closes issue: fixes #528
=> Migrate to Paho API Version 2

config-example.yaml, insteon_mqtt/cmd_line/util.py, insteon_mqtt/data/config-base.yaml, insteon_mqtt/data/config-schema.yaml, insteon_mqtt/network/Mqtt.py
Adds the following enable setting to `config.yaml`
```
mqtt:
encryption:
enable: False
```
Previously encryption was enabled by setting the `ca_cert` value.  But this is not necessary if your servers cert is from a trusted authority such as Let's Encrypt.
I added a deprecation warning to the documentation, but for the time being if `ca_cert` is set encryption will continue to be enabled even if `enable: False`.  This will only affect users who have enabled encryption previously and now attempt to disable it with `encryption: False`.  Since I suspect basically no one updates their config files with settings that are added in later, I doubt this will ever be an issue.
Also encryption seems to be a little used feature.
- This PR fixes or closes issue: fixes #535 
If user exposed …
=> Enable Optional Encryption Without CA_Cert

docs/battery_devices.md, docs/initializing.md, docs/mqtt.md, docs/scenes.md, insteon_mqtt/Modem.py
I remember why this was an issue and have updated issue #533.
In short battery devices are present, the sequence for the *_all command will halt when it gets to a battery device and only resume when that device has woken up and the command was sent.
This is at best confusing to the user, because they expect to see the sequence run to completion and receive a message like
"Refresh All Devices Complete"
At worst, this is problematic if a device after a battery device in the sequence is not getting the proper command and the user
assumes that it is.
_Note_
There is an alternative solution in which the commands are sent immediately to battery devices with the assumption that they are asleep and the command will be queued.  This seems bad to me as the devices may be awake, in which case they …
=> Remove Battery Devices from *_All Commands

config.json, docs/HA_Addon_Instructions.md, docs/configuration.md, docs/hassio_development.md, hassio/CONFIG-MOVED.txt, hassio/entrypoint.sh, hassio/webcli/app.py, insteon_mqtt/Modem.py, insteon_mqtt/log.py
The new location will be backed up by a Home Assistant snapshot and is Home Assistant's preferred location for storing config files going forward.
1. If a `config.yaml` file is __not__ found in the new location; AND
2. A `config.yaml` file is found at the old location; THEN
3. Copy the entire contents of the old config directory to the new one
4. Add a notice file to the old config directory telling users:
- The new location of their config files
- That they can delete these config files if everything is working correctly.
This process should ensure that no data is lost and should provide enough guidance to users on where their config files are located.
- This PR fixes or closes issue: fixes #532 
I have updated and added comments about the location of the new config files in every …
=> Migrate HomeAssistant Config Files Location

insteon_mqtt/data/config-base.yaml, insteon_mqtt/data/config-schema.yaml
This adds a couple of buttons (join, refresh, pair, and sync) to Home Assistant:
These buttons significantly improve the user experience when adding a device to Home Assistant.
The Log Sensor is not great, but is better than nothing.
These are only changes to the base config yaml file.
=> Add MQTT Discovery Entities for Config Buttons in Home Assistant
