doc/auto_start.md
doc/mqtt.md

Just things I saw while getting familiar with the design.

Fix a Few Typos in the Docs

---

config.yaml
doc/mqtt.md
insteon_mqtt/device/Leak.py
insteon_mqtt/mqtt/Leak.py
insteon_mqtt/mqtt/__init__.py

The new code has been tested over the weekend, dry and wet event still work OK and heartbeat is reported every 24 hours.

Add support for Leak Sensor heartbeat

---

tests/db/test_Device.py
tests/handler/test_Broadcast.py
tests/handler/test_DeviceDbGet.py
tests/handler/test_ModemDbGet.py
tests/handler/test_StandardCmd.py
tests/message/test_OutModemLinking.py
tests/message/test_OutModemScene.py
tests/message/test_OutResetPlm.py
tests/test_config.py

~~Fixes ~~about 12 of them, there are about 5 more broken ones.  I may get to them a little later.~~ all but one of them is fixed now.~~
All Pytest failures are fixed now.

Fix Broken Pytests

---

insteon_mqtt/device/Leak.py

I seems to have reversed the pairing for the leak sensor. Fix for setting that correctly.

Fix pairing for the leak sensor

---

insteon_mqtt/db/Device.py
insteon_mqtt/db/DeviceEntry.py
insteon_mqtt/db/DeviceModifyManagerI1.py
insteon_mqtt/db/__init__.py
tests/db/test_DeviceModifyManagerI1.py

Adds a manager to control the multi-message process.
Has full pytest coverage.

Add Support for Writing I1 DB Entries

---

docs/auto_start.md

Added info about tailing the service after it auto starts for debugging

Add Tail info

---

.gitignore
insteon_mqtt/device/Base.py
insteon_mqtt/device/KeypadLinc.py

some doc typo fixes and added vi swap files to the git ignore list

minor fixes

---

.gitignore
docs/CONTRIBUTING.md
insteon_mqtt/device/Base.py
insteon_mqtt/device/KeypadLinc.py
insteon_mqtt/util.py
tests/test_util.py

added some functionality and test cases to the util script to support upcoming modifications.

Util update

---

insteon_mqtt/handler/ThermostatCmd.py

Fix Typo In Thermostat Humidity

---

config.yaml

Fix FanLinc speed payload command in config.yaml

---

HISTORY.md
docs/mqtt.md
insteon_mqtt/device/Dimmer.py
insteon_mqtt/device/KeypadLinc.py
insteon_mqtt/util.py

Fixing a PR based off of master.
#235

PR 235 Rebased off of Dev

---

HISTORY.md
insteon_mqtt/handler/Base.py

Hops should increase by increments of 1 and max out at 3.

Improve Hop Calculation on Re-sending

---

HISTORY.md
insteon_mqtt/db/Device.py
insteon_mqtt/device/Motion.py
tests/device/test_MotionDev.py

Add Battery Support to 2844 Motion Models

---

insteon_mqtt/device/Thermostat.py
tests/db/test_DeviceEntry.py
tests/db/test_DeviceModifyManagerI1.py
tests/db/test_ModemEntry.py
tests/device/test_IOLincDev.py
tests/device/test_LeakDev.py
tests/device/test_ThermostatDev.py
tests/handler/test_Broadcast.py
tests/handler/test_BroadcastCmdResponse.py
tests/handler/test_ModemDbGet.py
tests/message/test_OutStandard.py
tests/mqtt/test_Remote.py

Add tests to a bunch of files that had only a few lines missing.

Add Unit Tests

---

CHANGELOG.md
insteon_mqtt/network/Stack.py

May help diagnose issues like #205

Improve Error Logging on Stack Exception

---

insteon_mqtt/device/BatterySensor.py
tests/device/test_MotionDev.py

Missed a bug from my log file.

Fix small bug 320

---

docs/mqtt.md

Update KPL Documentation Example to Match Config

---

CHANGELOG.md
insteon_mqtt/device/HiddenDoor.py

- Changes the hidden door sensor meta storage.  Only affect on users would be to make a check_battery request earlier than anticipated the first time after update.
- Updates the code to match the recent Refactored Base design.
I am merging this now as the current Hidden Door Sensor code may not function given the Refactor that just occurred.  There are no unit tests for the Hidden Door Sensor!  So I have to assume that everything works.  @tommycw1 since you have these devices can you pull the dev branch and confirm that this is working for you?  If there are issues please create an Issue.

Small Fixes to Hidden Door Sensor Code

---

CHANGELOG.md
docs/mqtt.md
insteon_mqtt/Modem.py
insteon_mqtt/cmd_line/main.py
insteon_mqtt/mqtt/Mqtt.py

Add a simple command to the command line and mqtt topics that returns the version of the program.  To be used for help and bug reporting.

Add Version Command

---

config-example.yaml
insteon_mqtt/mqtt/topic/DiscoveryTopic.py

A few small changes to the logging and the suggested config.

Discovery Tweaks and Fixes

---

tests/configs/use_dns.yaml

Yup, I failed to add the test config file.
- This PR fixes or closes issue: fixes #408

Add Missing File for Config Unit Test

---

insteon_mqtt/Modem.py
insteon_mqtt/cmd_line/modem.py
insteon_mqtt/config.py

Remove unused imports and add extra spaces.  I am sure I was the source of all of these.

Fix Various Flake Warnings

---

.bumpversion.cfg
CHANGELOG.md
README.md
config.json
insteon_mqtt/cmd_line/util.py
insteon_mqtt/const.py
insteon_mqtt/data/config-base.yaml
insteon_mqtt/device/KeypadLinc.py
insteon_mqtt/mqtt/Leak.py
setup.py
tests/device/test_KeypadLincDev.py
tests/mqtt/test_Leak.py

This release has a few of minor fixes and tweaks.

Version 1.0.2

---

insteon_mqtt/cmd_line/util.py
insteon_mqtt/mqtt/Leak.py

Fixing some flake errors that popped up.

Fix Flake Errors

---

insteon_mqtt/device/KeypadLinc.py

Was using level instead of is_on, which was causing the led_bit
variable to always be 0x00.
New Feature: Led Bit value is saved across reboots, hopefully will
cut down on the value getting out of sync.
- This PR fixes or closes issue: fixes #456

Use Is_On for Buttons; Save LED Bits to Meta

---

hassio/entrypoint.sh

Fix path in description.
Closes #485

Fix Path in Description
